### ISSUE TITLE
事前準備

### ISSUE THREAD

**Issue by shadow-moon** [shadow-moon/rails_tutorial#1]
# はじめに

チュートリアルを実施するための開発環境の設定について説明します。

:exclamation:  各自でrubyが実行できる環境をお持ちであれば、それをご利用ください。

途中で躓いてしまったり、わからないことがあれば、コメントをください。

# やること

* 開発用仮想環境の準備
* Rubyのインストール

# 開発用仮想環境の準備

## VirtualBox をダウンロード

[VirtualBoxの公式サイト](https://www.virtualbox.org/)からインストーラーをダウンロードし、インストールを実行してください。

## VMをダウンロード

[こちらのDropBox](https://www.dropbox.com/sh/j7n1ha8lvqmfuua/AACnryVkJEojKJ7Ue7M3YH-ia)から下記ファイルをダウンロード

* codeal_rails.vbox
* codeal_rails-disk1.vmdk

## VMを起動してログイン

先ほどダウンロードしたcoceal_rails.vbox をダブルクリック等で起動。

## vagrant ユーザーでログイン

VMを起動すると、vagrantユーザーのパスワード入力を求められるので、vagrantを入力。

<img width="1165" alt="codeal_rails_vm_login" src="https://cloud.githubusercontent.com/assets/7724443/10266252/887bf668-6a91-11e5-8a4f-3ab5fdcc0df5.png">

## ログイン後の画面

ログイン後、下記のような画面が見えれば、環境の設定は成功です。

<img width="1164" alt="codeal_rails_ubuntu_default" src="https://cloud.githubusercontent.com/assets/7724443/10266272/69c97352-6a92-11e5-9951-16c67cf89b34.png">

## （オプション）キーボードのレイアウトを変更する

デフォルトでは、英字配列になっているので、必要であれば日本語配列に変更する。

### System Settings を起動

<img width="1164" alt="codeal_rails_open_system_settings" src="https://cloud.githubusercontent.com/assets/7724443/10266277/ccc53aa4-6a92-11e5-8ce2-0c241d86893e.png">

### Keyboard layout を選択

<img width="744" alt="codeal_rails_keyboard_layout" src="https://cloud.githubusercontent.com/assets/7724443/10266300/d51366b2-6a93-11e5-95d9-5f8443456d08.png">

### 現在のレイアウトを確認

English のみになっていれば、 :heavy_plus_sign: をクリック。

<img width="737" alt="codeal_rails_confirm_keyboard_layout" src="https://cloud.githubusercontent.com/assets/7724443/10266338/549313aa-6a95-11e5-8206-b7c9dced568e.png">

### Japaneseを追加

<img width="716" alt="codeal_rails_add_japanese_keyboard_layout" src="https://cloud.githubusercontent.com/assets/7724443/10266339/67097ad8-6a95-11e5-9eb7-36f4ccd53eea.png">

### Japanese をレイアウトとして選択

<img width="739" alt="codeal_rails_choose_japanese_layout" src="https://cloud.githubusercontent.com/assets/7724443/10266346/a9b5399e-6a95-11e5-9cea-d1be671200fb.png">

## （オプション）日本語を入力できるようにする。

[こちらの記事](http://pgnote.net/?p=2182)を参考にセットアップしてください。

----

# Rubyのインストール

Rubyをインストールするため、rbenvをまずセットアップします。

### Terminalを起動

<img width="1169" alt="codeal_rails_open_terminal" src="https://cloud.githubusercontent.com/assets/7724443/10266454/26c7ad4c-6a9e-11e5-9fe0-2939c70523d0.png">

### rbenv をインストール

```bash
$ git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
$ git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
$ echo 'export RBENV_ROOT="$HOME/.rbenv"' >> ~/.bashrc
$ echo 'export PATH="$RBENV_ROOT/bin:$PATH"' >> ~/.bashrc
$ echo 'eval "$(rbenv init -)"' >> ~/.bashrc
$ echo 'install: --no-ri --no-rdoc' >> ~/.gemrc
```

ここまで実行したら、一旦、Terminalを終了し、再度起動する。

## ruby をインストール

`rbenv`コマンドを用いて、ruby の最新（現時点で2.2.3）をインストールする。

```bash
$ rbenv install 2.2.3
```

## デフォルトで使用するrubyのバージョンを指定

下記を実行することで、デフォルトで使用するrubyのバージョンを指定します。

```bash
$ rbenv local 2.2.3
```

`ruby` コマンドでバージョンが指定されたものと一致していることを確認します。

```bash
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [i686-linux]
```

# おわりに

何かわからないことや、行き詰まったりしたら、コメントを下さい。

**Comment by enotai** [comment]
OS X 10.10上にRuby 2.0.0p481が付属しており、これとgemでRails 4.2.3をインストールしたのですがRubyのバージョンは問題無いでしょうか。

**Comment by shadow-moon** [comment]
@enotai Rubyのバージョン、Railsのバージョンはどちらも問題無いと思います。
今回のハンズオンでは、「最新のバージョンでしか出来ないこと」のようなものは含んでおりません。
VM自体は、WindowsなどUnix系ではない環境の方向け、または自分で環境構築が難しい方向けですので、ご自身で普段使いやすいエディタや端末等があれば、それらをお使いください。

**Comment by johnmanjiro** [comment]
VMをダウンロードするために、ドロップボックスのURLにいっても「This account's public links are generating too much traffic and have been temporarily disabled!」と表示されます。どうしたらいいでしょうか？

**Comment by kotarofukuo** [comment]
Dropboxがエラーになってしまうのですが...

**Comment by shadow-moon** [comment]
@johnmanjiro @kotarofukuo 

DropBoxからだとダウンロードに制限がかかってしまっているようなので、別途方法を用意します。申し訳ありません。

**Comment by johnmanjiro** [comment]
osがmacではなくwindowsなので、terminalではなくコマンドプロンプトで代用しても大丈夫でしょうか？

**Comment by shadow-moon** [comment]
@johnmanjiro OSはlinux 系を想定しております。Windows版のrubyをインストール、設定は事前にご自身でしていただけないでしょうか。

https://www.ruby-lang.org/ja/documentation/installation/

ただ、明日のチュートリアルの内容がWindowsのRuby上で行えるかどうかは未確認であります。

**Comment by shadow-moon** [comment]
@johnmanjiro @kotarofukuo 

Vagrant からVMを作成する手順を用意いたしました。
https://github.com/shadow-moon/rails_tutorial/tree/master/vagrant

もし、お時間がありましたら事前に実施をお願いします。
他にもVM、ないし開発環境が整っていない方もいると思われるので、明日はrubyのインストール手順から開始します。
